"""migrate_subjects_to_library_subjects

Revision ID: d075be53c8ed
Revises: 362e2624da3e
Create Date: 2025-11-13 23:21:09.392057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd075be53c8ed'
down_revision: Union[str, Sequence[str], None] = '362e2624da3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Step 1: Drop all foreign key constraints FIRST (before dropping the table)
    op.drop_constraint(op.f('articles_subject_id_fkey'), 'articles', type_='foreignkey')
    op.drop_constraint(op.f('assessments_subject_id_fkey'), 'assessments', type_='foreignkey')
    op.drop_constraint(op.f('gemini_files_subject_id_fkey'), 'gemini_files', type_='foreignkey')
    op.drop_constraint(op.f('item_bank_subject_id_fkey'), 'item_bank', type_='foreignkey')
    op.drop_constraint(op.f('materials_subject_id_fkey'), 'materials', type_='foreignkey')
    op.drop_constraint(op.f('projects_subject_id_fkey'), 'projects', type_='foreignkey')
    
    # Check if chat_sessions table has subject_id foreign key
    bind = op.get_bind()
    result = bind.execute(
        sa.text(
            """
            SELECT EXISTS (
                SELECT 1 FROM information_schema.table_constraints 
                WHERE constraint_name = 'chat_sessions_subject_id_fkey' 
                AND table_name = 'chat_sessions'
            )
            """
        )
    )
    has_chat_fk = result.scalar()
    if has_chat_fk:
        op.drop_constraint('chat_sessions_subject_id_fkey', 'chat_sessions', type_='foreignkey')
    
    # Step 2: Now drop the subjects table (no dependencies left)
    op.drop_index(op.f('ix_subjects_id'), table_name='subjects')
    op.drop_table('subjects')
    
    # Step 3: Create new foreign keys pointing to library_subjects
    op.create_foreign_key(None, 'articles', 'library_subjects', ['subject_id'], ['id'])
    op.create_foreign_key(None, 'assessments', 'library_subjects', ['subject_id'], ['id'])
    op.create_foreign_key(None, 'gemini_files', 'library_subjects', ['subject_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'item_bank', 'library_subjects', ['subject_id'], ['id'])
    op.create_foreign_key(None, 'materials', 'library_subjects', ['subject_id'], ['id'])
    op.create_foreign_key(None, 'projects', 'library_subjects', ['subject_id'], ['id'])
    # Check if chat_sessions table has subject_id foreign key
    bind = op.get_bind()
    result = bind.execute(
        sa.text(
            """
            SELECT EXISTS (
                SELECT 1 FROM information_schema.table_constraints 
                WHERE constraint_name = 'chat_sessions_subject_id_fkey' 
                AND table_name = 'chat_sessions'
            )
            """
        )
    )
    has_chat_fk = result.scalar()
    if has_chat_fk:
        op.create_foreign_key(None, 'chat_sessions', 'library_subjects', ['subject_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.create_foreign_key(op.f('projects_subject_id_fkey'), 'projects', 'subjects', ['subject_id'], ['id'])
    op.drop_constraint(None, 'materials', type_='foreignkey')
    op.create_foreign_key(op.f('materials_subject_id_fkey'), 'materials', 'subjects', ['subject_id'], ['id'])
    op.drop_constraint(None, 'item_bank', type_='foreignkey')
    op.create_foreign_key(op.f('item_bank_subject_id_fkey'), 'item_bank', 'subjects', ['subject_id'], ['id'])
    op.drop_constraint(None, 'gemini_files', type_='foreignkey')
    op.create_foreign_key(op.f('gemini_files_subject_id_fkey'), 'gemini_files', 'subjects', ['subject_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'assessments', type_='foreignkey')
    op.create_foreign_key(op.f('assessments_subject_id_fkey'), 'assessments', 'subjects', ['subject_id'], ['id'])
    op.drop_constraint(None, 'articles', type_='foreignkey')
    op.create_foreign_key(op.f('articles_subject_id_fkey'), 'articles', 'subjects', ['subject_id'], ['id'])
    # Check if chat_sessions has foreign key to library_subjects
    bind = op.get_bind()
    result = bind.execute(
        sa.text(
            """
            SELECT EXISTS (
                SELECT 1 FROM information_schema.table_constraints 
                WHERE constraint_name LIKE '%chat_sessions%subject%' 
                AND table_name = 'chat_sessions'
            )
            """
        )
    )
    has_chat_fk = result.scalar()
    if has_chat_fk:
        op.drop_constraint(None, 'chat_sessions', type_='foreignkey')
        op.create_foreign_key('chat_sessions_subject_id_fkey', 'chat_sessions', 'subjects', ['subject_id'], ['id'], ondelete='SET NULL')
    op.create_table('subjects',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('domain_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('class_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], name=op.f('subjects_class_id_fkey')),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], name=op.f('subjects_domain_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('subjects_pkey'))
    )
    op.create_index(op.f('ix_subjects_id'), 'subjects', ['id'], unique=False)
    # ### end Alembic commands ###
